package com.leo.poemapp.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.leo.poemapp.model.Poem;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "POEM".
*/
public class PoemDao extends AbstractDao<Poem, Long> {

    public static final String TABLENAME = "POEM";

    /**
     * Properties of entity Poem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property First = new Property(1, String.class, "first", false, "FIRST");
        public final static Property Second = new Property(2, String.class, "second", false, "SECOND");
        public final static Property Count = new Property(3, int.class, "count", false, "COUNT");
        public final static Property Type = new Property(4, int.class, "type", false, "TYPE");
    }


    public PoemDao(DaoConfig config) {
        super(config);
    }
    
    public PoemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"POEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"FIRST\" TEXT," + // 1: first
                "\"SECOND\" TEXT," + // 2: second
                "\"COUNT\" INTEGER NOT NULL ," + // 3: count
                "\"TYPE\" INTEGER NOT NULL );"); // 4: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"POEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Poem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String first = entity.getFirst();
        if (first != null) {
            stmt.bindString(2, first);
        }
 
        String second = entity.getSecond();
        if (second != null) {
            stmt.bindString(3, second);
        }
        stmt.bindLong(4, entity.getCount());
        stmt.bindLong(5, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Poem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String first = entity.getFirst();
        if (first != null) {
            stmt.bindString(2, first);
        }
 
        String second = entity.getSecond();
        if (second != null) {
            stmt.bindString(3, second);
        }
        stmt.bindLong(4, entity.getCount());
        stmt.bindLong(5, entity.getType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Poem readEntity(Cursor cursor, int offset) {
        Poem entity = new Poem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // first
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // second
            cursor.getInt(offset + 3), // count
            cursor.getInt(offset + 4) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Poem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setFirst(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSecond(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCount(cursor.getInt(offset + 3));
        entity.setType(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Poem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Poem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Poem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
